### ISSUE TITLE
Sorry I couldn't reach you any other way, but...

### ISSUE THREAD

**Issue by liamzee** [aavogt/aavogt.github.io#1]
I'd have contacted you on Bitbucket, but I'm having issues with networking right now (based in China), but I notice you're one of the maintainers for HList (and Gwern seems to be cutting down on his involvement in maintainership). The hackage package no longer builds with the latest GHCs (9.4 / 9.6), and I'm wondering if you might be interested in updating it, or if circumstances no longer permit, whether you might wish to give it up to Haskell Github Trust or some other maintainer.

**Comment by aavogt** [comment]
Record.hs compiles with 9.6.1 after:
```
diff --git a/Data/HList/Record.hs b/Data/HList/Record.hs
index b45d380..0c164bd 100644
--- a/Data/HList/Record.hs
+++ b/Data/HList/Record.hs
@@ -471,6 +471,7 @@ instance (HMapCxt HList ReadComponent (AddProxy rs) bs,
           ApplyAB ReadComponent (Proxy r) readP_r,
           HProxies rs,
           HSequence ReadP (readP_r ': bs) (r ': rs),
+          readP_r ~ ReadP (Tagged l v),
 
           -- ghc-8.0.2 needs these. The above constraints
           -- should imply them
diff --git a/HList.cabal b/HList.cabal
index 1e54711..ca1b454 100644
--- a/HList.cabal
+++ b/HList.cabal
@@ -58,7 +58,7 @@ flag new_type_eq
                See <https://ghc.haskell.org/trac/ghc/ticket/9918>
 
 library
-  Build-Depends:       base >= 4.6 && < 4.17,
+  Build-Depends:       base >= 4.6 && < 4.19,
                        -- for Typeable '[] and '(:) with ghc-7.6
                        base-orphans,
                        -- Data.Semigroup for ghc < 8
```
if the tests pass I'll upload a new version.

**Comment by aavogt** [comment]
I've uploaded a new version. Note that the tests pass with 9.6.1 but not with 9.4.6.

**Comment by liamzee** [comment]
Thanks for your time, and sorry for the trouble. Working adequately on 9.6.2. :)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
